# Generated by Django 5.0 on 2023-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
