# Generated by Django 5.0 on 2024-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0003_alter_endereco_bairro_alter_endereco_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='logradouro',
        ),
    ]
