# Generated by Django 5.0 on 2024-02-08 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0013_alter_pagamento_quant_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
