# Generated by Django 5.0 on 2024-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
