# Generated by Django 5.0 on 2024-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0010_alter_customuser_options_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valido_ate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
