# Generated by Django 5.0 on 2024-02-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0012_pagamento_quant_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='quant_acesso',
            field=models.IntegerField(default=0),
        ),
    ]
