# Generated by Django 5.0 on 2024-02-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0014_alter_pagamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
