# Generated by Django 5.0 on 2024-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0017_alter_pagamento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('chave_pix', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='codigo_pagamento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
