# Generated by Django 5.0 on 2024-02-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao_app', '0018_pagamentopix_pagamento_codigo_pagamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagamentoPix',
        ),
    ]
