name: GetOptimiza
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para meu servidor
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOVE_HOST }}
          REMOTE_USER: ${{ secrets.REMOVE_USER }}
          REMOTE_PORT: ${{ secrets.REMOVE_PORT }}
          TARGET: ${{ secrets.REMOVE_TARGET }}